spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/cat_base

  flyway:
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/university_db

server:
  port: 8080